/********************************************************************
* ViewerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ViewerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableViewerDict();
extern void G__cpp_setup_inheritanceViewerDict();
extern void G__cpp_setup_typetableViewerDict();
extern void G__cpp_setup_memvarViewerDict();
extern void G__cpp_setup_globalViewerDict();
extern void G__cpp_setup_memfuncViewerDict();
extern void G__cpp_setup_funcViewerDict();
extern void G__set_cpp_environmentViewerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Viewer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ViewerDictLN_TClass;
extern G__linked_taginfo G__ViewerDictLN_TBuffer;
extern G__linked_taginfo G__ViewerDictLN_TMemberInspector;
extern G__linked_taginfo G__ViewerDictLN_TObject;
extern G__linked_taginfo G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ViewerDictLN_TGObject;
extern G__linked_taginfo G__ViewerDictLN_TQObject;
extern G__linked_taginfo G__ViewerDictLN_TGWindow;
extern G__linked_taginfo G__ViewerDictLN_TGFrame;
extern G__linked_taginfo G__ViewerDictLN_TGCompositeFrame;
extern G__linked_taginfo G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ViewerDictLN_TGVerticalFrame;
extern G__linked_taginfo G__ViewerDictLN_TGMainFrame;
extern G__linked_taginfo G__ViewerDictLN_TCanvas;
extern G__linked_taginfo G__ViewerDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__ViewerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ViewerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ViewerDictLN_TH1;
extern G__linked_taginfo G__ViewerDictLN_TGTab;
extern G__linked_taginfo G__ViewerDictLN_View;
extern G__linked_taginfo G__ViewerDictLN_Viewer;

/* STUB derived class for protected member access */
