//
// File generated by /opt/root/5.22.00/bin/rootcint at Fri Jul 17 09:40:43 2009

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ViewerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Viewer_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_Viewer(void *p);
   static void deleteArray_Viewer(void *p);
   static void destruct_Viewer(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Viewer*)
   {
      ::Viewer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Viewer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Viewer", ::Viewer::Class_Version(), "Viewer.h", 21,
                  typeid(::Viewer), DefineBehavior(ptr, ptr),
                  &::Viewer::Dictionary, isa_proxy, 0,
                  sizeof(::Viewer) );
      instance.SetDelete(&delete_Viewer);
      instance.SetDeleteArray(&deleteArray_Viewer);
      instance.SetDestructor(&destruct_Viewer);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Viewer*)
   {
      return GenerateInitInstanceLocal((::Viewer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Viewer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Viewer::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Viewer::Class_Name()
{
   return "Viewer";
}

//______________________________________________________________________________
const char *Viewer::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Viewer::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Viewer::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Viewer::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Viewer*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Viewer::Streamer(TBuffer &R__b)
{
   // Stream an object of class Viewer.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TGMainFrame::Streamer(R__b);
      R__b.ReadStaticArray((char*)ViewerName);
      R__b >> currentView;
      R__b >> fNTab;
      R__b >> fCurrentTabForAdding;
      R__b >> fTab;
      R__b >> fCurrentFrame;
      int R__i;
      for (R__i = 0; R__i < 20; R__i++)
         R__b >> fECanvas[R__i];
      for (R__i = 0; R__i < 20; R__i++)
         R__b >> buttonFrame[R__i];
      R__b.ReadStaticArray((bool*)fFwdBwdButtons);
      R__b >> nView;
      for (R__i = 0; R__i < 500; R__i++)
         ;//R__b.ReadArray(vname);
      R__b.ReadStaticArray((int*)ncol);
      R__b.ReadStaticArray((int*)nrow);
      R__b.ReadStaticArray((int*)nHistView);
      R__b.ReadStaticArray((int*)viewType);
      R__b.ReadStaticArray((int*)tabNr);
      for (R__i = 0; R__i < 6000; R__i++)
         R__b >> histView[0][R__i];
      for (R__i = 0; R__i < 500; R__i++)
         R__b >> extView[R__i];
      R__b.CheckByteCount(R__s, R__c, Viewer::IsA());
   } else {
      R__c = R__b.WriteVersion(Viewer::IsA(), kTRUE);
      TGMainFrame::Streamer(R__b);
      R__b.WriteArray(ViewerName, 50);
      R__b << currentView;
      R__b << fNTab;
      R__b << fCurrentTabForAdding;
      R__b << fTab;
      R__b << fCurrentFrame;
      int R__i;
      for (R__i = 0; R__i < 20; R__i++)
         R__b << fECanvas[R__i];
      for (R__i = 0; R__i < 20; R__i++)
         R__b << buttonFrame[R__i];
      R__b.WriteArray(fFwdBwdButtons, 20);
      R__b << nView;
      for (R__i = 0; R__i < 500; R__i++)
         ;//R__b.WriteArray(vname, __COUNTER__);
      R__b.WriteArray(ncol, 500);
      R__b.WriteArray(nrow, 500);
      R__b.WriteArray(nHistView, 500);
      R__b.WriteArray(viewType, 500);
      R__b.WriteArray(tabNr, 500);
      for (R__i = 0; R__i < 6000; R__i++)
         R__b << histView[0][R__i];
      for (R__i = 0; R__i < 500; R__i++)
         R__b << extView[R__i];
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void Viewer::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class Viewer.
      TClass *R__cl = ::Viewer::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "ViewerName[50]", ViewerName);
      R__insp.Inspect(R__cl, R__parent, "currentView", &currentView);
      R__insp.Inspect(R__cl, R__parent, "fNTab", &fNTab);
      R__insp.Inspect(R__cl, R__parent, "fCurrentTabForAdding", &fCurrentTabForAdding);
      R__insp.Inspect(R__cl, R__parent, "*fTab", &fTab);
      R__insp.Inspect(R__cl, R__parent, "*fCurrentFrame", &fCurrentFrame);
      R__insp.Inspect(R__cl, R__parent, "*fECanvas[20]", &fECanvas);
      R__insp.Inspect(R__cl, R__parent, "*buttonFrame[20]", &buttonFrame);
      R__insp.Inspect(R__cl, R__parent, "fFwdBwdButtons[20]", fFwdBwdButtons);
      R__insp.Inspect(R__cl, R__parent, "nView", &nView);
      R__insp.Inspect(R__cl, R__parent, "*vname[500]", &vname);
      R__insp.Inspect(R__cl, R__parent, "ncol[500]", ncol);
      R__insp.Inspect(R__cl, R__parent, "nrow[500]", nrow);
      R__insp.Inspect(R__cl, R__parent, "nHistView[500]", nHistView);
      R__insp.Inspect(R__cl, R__parent, "viewType[500]", viewType);
      R__insp.Inspect(R__cl, R__parent, "tabNr[500]", tabNr);
      R__insp.Inspect(R__cl, R__parent, "*histView[500][12]", &histView);
      R__insp.Inspect(R__cl, R__parent, "*extView[500]", &extView);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_Viewer(void *p) {
      delete ((::Viewer*)p);
   }
   static void deleteArray_Viewer(void *p) {
      delete [] ((::Viewer*)p);
   }
   static void destruct_Viewer(void *p) {
      typedef ::Viewer current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Viewer

/********************************************************
* ViewerDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableViewerDict();

extern "C" void G__set_cpp_environmentViewerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Viewer.h");
  G__cpp_reset_tagtableViewerDict();
}
#include <new>
extern "C" int G__cpp_dllrevViewerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Viewer */
static int G__ViewerDict_321_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Viewer* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Viewer(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (const char*) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) Viewer(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (const char*) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Viewer(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) Viewer(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ViewerDictLN_Viewer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((Viewer*) G__getstructoffset())->getCanvas());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->ByeBye();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->Inc();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->Dec();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->DoDraw((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->DoSelect((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((Viewer*) G__getstructoffset())->configureButtons((int) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((Viewer*) G__getstructoffset())->configureButtons();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->show();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 9:
      ((Viewer*) G__getstructoffset())->addView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7])
, (TH1*) G__int(libp->para[8]));
      G__setnull(result7);
      break;
   case 8:
      ((Viewer*) G__getstructoffset())->addView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((Viewer*) G__getstructoffset())->addView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]));
      G__setnull(result7);
      break;
   case 6:
      ((Viewer*) G__getstructoffset())->addView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5]));
      G__setnull(result7);
      break;
   case 5:
      ((Viewer*) G__getstructoffset())->addView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3])
, (TH1*) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((Viewer*) G__getstructoffset())->addView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (TH1*) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((Viewer*) G__getstructoffset())->addView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 12:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7])
, (TH1*) G__int(libp->para[8]), (TH1*) G__int(libp->para[9])
, (TH1*) G__int(libp->para[10]), (TH1*) G__int(libp->para[11]));
      G__setnull(result7);
      break;
   case 11:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7])
, (TH1*) G__int(libp->para[8]), (TH1*) G__int(libp->para[9])
, (TH1*) G__int(libp->para[10]));
      G__setnull(result7);
      break;
   case 10:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7])
, (TH1*) G__int(libp->para[8]), (TH1*) G__int(libp->para[9]));
      G__setnull(result7);
      break;
   case 9:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7])
, (TH1*) G__int(libp->para[8]));
      G__setnull(result7);
      break;
   case 8:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]), (TH1*) G__int(libp->para[7]));
      G__setnull(result7);
      break;
   case 7:
      ((Viewer*) G__getstructoffset())->addOverlayView(
(const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5])
, (TH1*) G__int(libp->para[6]));
      G__setnull(result7);
      break;
   case 6:
      ((Viewer*) G__getstructoffset())->addOverlayView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]), (TH1*) G__int(libp->para[5]));
      G__setnull(result7);
      break;
   case 5:
      ((Viewer*) G__getstructoffset())->addOverlayView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3])
, (TH1*) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ((Viewer*) G__getstructoffset())->addOverlayView((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Float_t) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->addView((const char*) G__int(libp->para[0]), (View*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->addTab((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->addFwdBwdButtons();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Viewer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Viewer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Viewer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Viewer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Viewer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Viewer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ViewerDict_321_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Viewer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Viewer G__TViewer;
static int G__ViewerDict_321_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Viewer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Viewer*) (soff+(sizeof(Viewer)*i)))->~G__TViewer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Viewer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Viewer*) (soff))->~G__TViewer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Viewer */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncViewerDict {
 public:
  G__Sizep2memfuncViewerDict(): p(&G__Sizep2memfuncViewerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncViewerDict::*p)();
};

size_t G__get_sizep2memfuncViewerDict()
{
  G__Sizep2memfuncViewerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceViewerDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ViewerDictLN_Viewer))) {
     Viewer *G__Lderived;
     G__Lderived=(Viewer*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),G__get_linked_tagnum(&G__ViewerDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableViewerDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ViewerDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ViewerDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Viewer */
static void G__setup_memvarViewer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer));
   { Viewer *p; p=(Viewer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,1,-1,-1,-2,4,"nTabMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,1,-1,-1,-2,4,"nViewMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,4,"ViewerName[50]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"currentView=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fNTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fCurrentTabForAdding=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TGTab),-1,-1,4,"fTab=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TGCompositeFrame),-1,-1,4,"fCurrentFrame=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TRootEmbeddedCanvas),-1,-1,4,"fECanvas[20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TGVerticalFrame),-1,-1,4,"buttonFrame[20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"fFwdBwdButtons[20]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nView=",0,(char*)NULL);
   G__memvar_setup((void*)0,67,0,0,-1,-1,-1,4,"vname[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"ncol[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nrow[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nHistView[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"viewType[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"tabNr[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TH1),-1,-1,4,"histView[500][12]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_View),-1,-1,4,"extView[500]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ViewerDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarViewerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncViewer(void) {
   /* Viewer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer));
   G__memfunc_setup("Viewer",626,G__ViewerDict_321_0_1, 105, G__get_linked_tagnum(&G__ViewerDictLN_Viewer), -1, 0, 4, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h C - - 10 '\"Viewer\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getCanvas",924,G__ViewerDict_321_0_2, 85, G__get_linked_tagnum(&G__ViewerDictLN_TCanvas), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ByeBye",576,G__ViewerDict_321_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__ViewerDict_321_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Inc",282,G__ViewerDict_321_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Dec",268,G__ViewerDict_321_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__ViewerDict_321_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSelect",787,G__ViewerDict_321_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("configureButtons",1713,G__ViewerDict_321_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 '0' tab", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("show",449,G__ViewerDict_321_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addView",708,G__ViewerDict_321_0_11, 121, -1, -1, 0, 9, 1, 1, 0, 
"C - - 10 - s i - 'Int_t' 0 - ncol "
"i - 'Int_t' 0 - nrow U 'TH1' - 0 'NULL' h1 "
"U 'TH1' - 0 'NULL' h2 U 'TH1' - 0 'NULL' h3 "
"U 'TH1' - 0 'NULL' h4 U 'TH1' - 0 'NULL' h5 "
"U 'TH1' - 0 'NULL' h6", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addOverlayView",1446,G__ViewerDict_321_0_12, 121, -1, -1, 0, 12, 1, 1, 0, 
"C - - 10 - s i - 'Int_t' 0 - col "
"i - 'Int_t' 0 - row f - 'Float_t' 0 - scale "
"U 'TH1' - 0 'NULL' h1a U 'TH1' - 0 'NULL' h1b "
"U 'TH1' - 0 'NULL' h2a U 'TH1' - 0 'NULL' h2b "
"U 'TH1' - 0 'NULL' h3a U 'TH1' - 0 'NULL' h3b "
"U 'TH1' - 0 'NULL' h4a U 'TH1' - 0 'NULL' h4b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addView",708,G__ViewerDict_321_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - s U 'View' - 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addTab",576,G__ViewerDict_321_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - tabName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addFwdBwdButtons",1622,G__ViewerDict_321_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ViewerDict_321_0_16, 85, G__get_linked_tagnum(&G__ViewerDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&Viewer::Class), 0);
   G__memfunc_setup("Class_Name",982,G__ViewerDict_321_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&Viewer::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__ViewerDict_321_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&Viewer::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__ViewerDict_321_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&Viewer::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ViewerDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ViewerDict_321_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ViewerDict_321_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&Viewer::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ViewerDict_321_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&Viewer::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__ViewerDict_321_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&Viewer::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ViewerDict_321_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&Viewer::DeclFileLine), 0);
   // automatic destructor
   G__memfunc_setup("~Viewer", 752, G__ViewerDict_321_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncViewerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalViewerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcViewerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ViewerDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ViewerDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_TGTab = { "TGTab" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_View = { "View" , 99 , -1 };
G__linked_taginfo G__ViewerDictLN_Viewer = { "Viewer" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableViewerDict() {
  G__ViewerDictLN_TClass.tagnum = -1 ;
  G__ViewerDictLN_TBuffer.tagnum = -1 ;
  G__ViewerDictLN_TMemberInspector.tagnum = -1 ;
  G__ViewerDictLN_TObject.tagnum = -1 ;
  G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ViewerDictLN_TGObject.tagnum = -1 ;
  G__ViewerDictLN_TQObject.tagnum = -1 ;
  G__ViewerDictLN_TGWindow.tagnum = -1 ;
  G__ViewerDictLN_TGFrame.tagnum = -1 ;
  G__ViewerDictLN_TGCompositeFrame.tagnum = -1 ;
  G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ViewerDictLN_TGVerticalFrame.tagnum = -1 ;
  G__ViewerDictLN_TGMainFrame.tagnum = -1 ;
  G__ViewerDictLN_TCanvas.tagnum = -1 ;
  G__ViewerDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__ViewerDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ViewerDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ViewerDictLN_TH1.tagnum = -1 ;
  G__ViewerDictLN_TGTab.tagnum = -1 ;
  G__ViewerDictLN_View.tagnum = -1 ;
  G__ViewerDictLN_Viewer.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableViewerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TH1);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_TGTab);
   G__get_linked_tagnum_fwd(&G__ViewerDictLN_View);
   G__tagtable_setup(G__get_linked_tagnum(&G__ViewerDictLN_Viewer),sizeof(Viewer),-1,62464,"a simple histogram viewer",G__setup_memvarViewer,G__setup_memfuncViewer);
}
extern "C" void G__cpp_setupViewerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupViewerDict()");
  G__set_cpp_environmentViewerDict();
  G__cpp_setup_tagtableViewerDict();

  G__cpp_setup_inheritanceViewerDict();

  G__cpp_setup_typetableViewerDict();

  G__cpp_setup_memvarViewerDict();

  G__cpp_setup_memfuncViewerDict();
  G__cpp_setup_globalViewerDict();
  G__cpp_setup_funcViewerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncViewerDict();
  return;
}
class G__cpp_setup_initViewerDict {
  public:
    G__cpp_setup_initViewerDict() { G__add_setup_func("ViewerDict",(G__incsetup)(&G__cpp_setupViewerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initViewerDict() { G__remove_setup_func("ViewerDict"); }
};
G__cpp_setup_initViewerDict G__cpp_setup_initializerViewerDict;

